from datetime import datetime, date
from sqlalchemy import String,Integer,Float,DateTime,Date,ForeignKey,Text,Boolean
from sqlalchemy.orm import Mapped,mapped_column,relationship
from .database import Base
class Stamp:
 created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
 updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
class User(Base,Stamp):
 __tablename__="users"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(120)); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[str]=mapped_column(default="student"); preferred_language:Mapped[str]=mapped_column(default="en"); country:Mapped[str]=mapped_column(default="")
class StudentProfile(Base,Stamp):
 __tablename__="profiles"; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id"),unique=True); birth_year:Mapped[int|None]; country:Mapped[str]=mapped_column(default=""); city:Mapped[str]=mapped_column(default=""); education_level:Mapped[str]=mapped_column(default="HIGH_SCHOOL"); grade_year:Mapped[str]=mapped_column(default=""); gpa:Mapped[float|None]; gpa_scale:Mapped[float]=mapped_column(default=4); english_level:Mapped[str]=mapped_column(default="B2"); ielts_score:Mapped[float|None]; sat_score:Mapped[int|None]; budget_level:Mapped[str]=mapped_column(default="LOW"); preferred_countries:Mapped[str]=mapped_column(Text,default="[]"); preferred_fields:Mapped[str]=mapped_column(Text,default="[]"); skills:Mapped[str]=mapped_column(Text,default="[]"); interests:Mapped[str]=mapped_column(Text,default="[]"); achievements:Mapped[str]=mapped_column(Text,default=""); projects:Mapped[str]=mapped_column(Text,default=""); extracurriculars:Mapped[str]=mapped_column(Text,default=""); volunteering:Mapped[str]=mapped_column(Text,default=""); research_experience:Mapped[str]=mapped_column(Text,default=""); work_experience:Mapped[str]=mapped_column(Text,default="")
class Goal(Base,Stamp):
 __tablename__="goals"; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id")); title:Mapped[str]; goal_type:Mapped[str]=mapped_column(default="UNIVERSITY_ADMISSION"); target_field:Mapped[str]=mapped_column(default=""); target_countries:Mapped[str]=mapped_column(Text,default="[]"); target_date:Mapped[date|None]; funding_requirement:Mapped[str]=mapped_column(default="HIGH"); education_level:Mapped[str]=mapped_column(default="BACHELOR"); language:Mapped[str]=mapped_column(default="English"); description:Mapped[str]=mapped_column(Text,default=""); status:Mapped[str]=mapped_column(default="ACTIVE")
class Requirement(Base,Stamp):
 __tablename__="requirements"; id:Mapped[int]=mapped_column(primary_key=True); goal_id:Mapped[int]=mapped_column(ForeignKey("goals.id")); category:Mapped[str]; name:Mapped[str]; description:Mapped[str]=mapped_column(Text); target_value:Mapped[str]=mapped_column(default=""); importance:Mapped[str]=mapped_column(default="HIGH"); source_type:Mapped[str]=mapped_column(default="SYSTEM")
class ProfileGap(Base,Stamp):
 __tablename__="gaps"; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id")); goal_id:Mapped[int]=mapped_column(ForeignKey("goals.id")); requirement_id:Mapped[int|None]=mapped_column(ForeignKey("requirements.id")); category:Mapped[str]; title:Mapped[str]; description:Mapped[str]=mapped_column(Text); severity:Mapped[str]; current_state:Mapped[str]; target_state:Mapped[str]; status:Mapped[str]=mapped_column(default="OPEN"); evidence:Mapped[str]=mapped_column(Text); resolved_at:Mapped[datetime|None]
class Opportunity(Base,Stamp):
 __tablename__="opportunities"; id:Mapped[int]=mapped_column(primary_key=True); title:Mapped[str]; provider:Mapped[str]=mapped_column(default=""); opportunity_type:Mapped[str]; description:Mapped[str]=mapped_column(Text); official_url:Mapped[str]=mapped_column(default=""); country:Mapped[str]=mapped_column(default="International"); delivery_mode:Mapped[str]=mapped_column(default="UNKNOWN"); min_age:Mapped[int|None]; max_age:Mapped[int|None]; eligible_countries:Mapped[str]=mapped_column(Text,default="[]"); education_levels:Mapped[str]=mapped_column(Text,default="[]"); fields:Mapped[str]=mapped_column(Text,default="[]"); field_restriction:Mapped[bool]=mapped_column(Boolean,default=False); funding_type:Mapped[str]=mapped_column(default="UNKNOWN"); funding_amount_text:Mapped[str|None]=mapped_column(nullable=True,default=None); cost_text:Mapped[str|None]=mapped_column(nullable=True,default=None); language_requirements:Mapped[str|None]=mapped_column(nullable=True,default=None); deadline:Mapped[date|None]; start_date:Mapped[date|None]; end_date:Mapped[date|None]; requirements_text:Mapped[str]=mapped_column(Text,default=""); verified_at:Mapped[date|None]; source_label:Mapped[str]=mapped_column(default="Pathly Demo Dataset"); gap_categories:Mapped[str]=mapped_column(Text,default="[]"); source_url:Mapped[str]=mapped_column(default="",index=True); source_domain:Mapped[str]=mapped_column(default=""); source_type:Mapped[str]=mapped_column(default="DEMO"); verification_status:Mapped[str]=mapped_column(default="DEMO",index=True); discovered_at:Mapped[datetime|None]; canonical_source_url:Mapped[str|None]=mapped_column(nullable=True); discovery_source_url:Mapped[str|None]=mapped_column(nullable=True); source_quality:Mapped[str]=mapped_column(default="DEMO"); is_first_party:Mapped[bool]=mapped_column(Boolean,default=False); verification_notes:Mapped[str|None]=mapped_column(Text,nullable=True); last_checked_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True)
class Roadmap(Base,Stamp):
 __tablename__="roadmaps"; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id")); goal_id:Mapped[int]=mapped_column(ForeignKey("goals.id")); title:Mapped[str]
class RoadmapTask(Base,Stamp):
 __tablename__="roadmap_tasks"; id:Mapped[int]=mapped_column(primary_key=True); roadmap_id:Mapped[int]=mapped_column(ForeignKey("roadmaps.id")); opportunity_id:Mapped[int|None]=mapped_column(ForeignKey("opportunities.id")); gap_id:Mapped[int|None]=mapped_column(ForeignKey("gaps.id")); title:Mapped[str]; description:Mapped[str]=mapped_column(Text,default=""); category:Mapped[str]=mapped_column(default="APPLICATION"); priority:Mapped[str]=mapped_column(default="MEDIUM"); due_date:Mapped[date|None]; status:Mapped[str]=mapped_column(default="TODO"); estimated_minutes:Mapped[int]=mapped_column(default=30); completed_at:Mapped[datetime|None]
class ReadinessSnapshot(Base):
 __tablename__="readiness_snapshots"; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id")); goal_id:Mapped[int]=mapped_column(ForeignKey("goals.id")); overall_readiness:Mapped[float]; academic_readiness:Mapped[float]; language_readiness:Mapped[float]; experience_readiness:Mapped[float]; extracurricular_readiness:Mapped[float]; financial_readiness:Mapped[float]; application_readiness:Mapped[float]; created_at:Mapped[datetime]=mapped_column(default=datetime.utcnow)
class ApplicationDocument(Base,Stamp):
 __tablename__="documents"; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id")); opportunity_id:Mapped[int]=mapped_column(ForeignKey("opportunities.id")); document_type:Mapped[str]; title:Mapped[str]; content:Mapped[str]=mapped_column(Text)
class DocumentReview(Base):
 __tablename__="document_reviews"; id:Mapped[int]=mapped_column(primary_key=True); document_id:Mapped[int]=mapped_column(ForeignKey("documents.id")); overall_score:Mapped[float]; requirement_coverage:Mapped[str]=mapped_column(Text); strengths:Mapped[str]=mapped_column(Text); gaps:Mapped[str]=mapped_column(Text); recommendations:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(default=datetime.utcnow)
